# Generated by Django 3.1.7 on 2021-04-03 09:02

import apps.user.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[apps.user.validator.mobile_validator, apps.user.validator.mobile_length_validator], verbose_name='mobile number'),
        ),
    ]
