# Generated by Django 3.1.7 on 2021-03-10 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_status',
        ),
        migrations.AddField(
            model_name='user',
            name='friends_request',
            field=models.ManyToManyField(related_name='request', to=settings.AUTH_USER_MODEL),
        ),
    ]
